### ISSUE TITLE
dicttoxml dependency is dead upstream

### ISSUE THREAD

**Issue by asarubbo** [Salamek/huawei-lte-api#107]
Hello,

during the removal of downstream dicttoxml (because of dead upstream), we noticed that huawei-lte-api still uses it, here is an example of a replacement:

https://github.com/spulec/moto/commit/867fc3b7f7c6a53cba4249b1c1485c6c092e6b3f

**Comment by Salamek** [comment]
@asarubbo yea, i know about it and about `xmltodict.unparse` i was planning to refactor my code to use it... anyway good to have a issue here for it so i won't forgot :) Now i only need some time to be able to work on this project lol
