### ISSUE TITLE
Tesing the example

### ISSUE THREAD

**Issue by cagnulein** [Salamek/huawei-lte-api#11]
Traceback (most recent call last):
  File "router.py", line 1, in <module>
    from huawei_lte_api.Client import Client
  File "/home/pi/.local/lib/python2.7/site-packages/huawei_lte_api/Client.py", line 38
    def __init__(self, connection: Connection):

I'm just testing the example

**Comment by Salamek** [comment]
@cagnulein this is **Python3** project, python2 is frankenstein's monster (it is dead a few years but it is still walking somehow) please use **Python3** : 

For debian based distros:
```sh
apt update && apt install python3 python3-pip
pip3 install huawei-lte-api
python3 huawei_lte_api_test.py
```
