### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by Alexis000000** [Salamek/huawei-lte-api#111]
Hello,

I tried to install the API but an error occurred saying that the certificate is expired.
Is there anyway this can be solved ?

kindly

**Comment by Salamek** [comment]
@Alexis000000 install how? on what os?

**Comment by Salamek** [comment]
@Alexis000000 screenshot is not uploaded correctly...
Also, what version of ubuntu?

**Comment by Salamek** [comment]
@Alexis000000 my guess is that you are using old version of ubuntu with expired letsencrypt root cert:
https://superuser.com/questions/1679204/curl-on-ubuntu-14-all-lets-encrypt-certificates-are-expired-error-60

**Comment by Alexis000000** [comment]
I am using ubuntu 18.0.4

Here is the output of all the commands

xxxxxx:~$ sudo pip install huawei-lte-api
Requirement already satisfied: huawei-lte-api in /usr/local/lib/python3.8/dist-packages (1.5.2)
Requirement already satisfied: pycryptodomex in /usr/local/lib/python3.8/dist-packages (from huawei-lte-api) (3.10.4)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from huawei-lte-api) (2.22.0)
Requirement already satisfied: xmltodict in /usr/local/lib/python3.8/dist-packages (from huawei-lte-api) (0.12.0)
xxxxxxx~$ wget -O - https://repository.salamek.cz/deb/salamek.gpg.key|sudo apt-key add -
--2021-10-05 15:19:51--  https://repository.salamek.cz/deb/salamek.gpg.key
Resolving repository.salamek.cz (repository.salamek.cz)... 78.80.161.207
Connecting to repository.salamek.cz (repository.salamek.cz)|78.80.161.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1715 (1.7K) [application/octet-stream]
Saving to: ‘STDOUT’

-                                       100%[==============================================================================>]   1.67K  --.-KB/s    in 0s      

2021-10-05 15:19:51 (810 MB/s) - written to stdout [1715/1715]

OK
xxxxx:~$ echo "deb     https://repository.salamek.cz/deb/pub all main" | sudo tee /etc/apt/sources.list.d/salamek.cz.list
deb     https://repository.salamek.cz/deb/pub all main
xxxxxx:~$ sudo apt-get update
Hit:1 http://fr.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://fr.archive.ubuntu.com/ubuntu focal-updates InRelease                                  
Hit:3 http://ppa.launchpad.net/gnuradio/gnuradio-releases/ubuntu focal InRelease                   
Ign:4 https://repository.salamek.cz/deb/pub all InRelease                                                                                           
Hit:5 http://fr.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                                 
Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease                                    
Hit:7 http://ppa.launchpad.net/mormj/gnuradio-releases-3.8/ubuntu focal InRelease                   
Err:8 https://repository.salamek.cz/deb/pub all Release                      
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 78.80.161.207 443]
Reading package lists... Done                          
E: The repository 'https://repository.salamek.cz/deb/pub all Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Salamek** [comment]
1) You can install this package by PIP OR by APT, you don't need to do both
2) And you have same issue as is mentioned on this URL https://superuser.com/questions/1679204/curl-on-ubuntu-14-all-lets-encrypt-certificates-are-expired-error-60 so please follow steps on the URL to fix it, this is common issue these days (https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)

**Comment by Alexis000000** [comment]
Thank you!
I installed it successfully but I still don't have the huawei-lte directory downloaded.

**Comment by Salamek** [comment]
@Alexis000000 umm huawei_lte_api is a python package, so just include it using:

```python
from huawei_lte_api.Client import Client
from huawei_lte_api.Connection import Connection
...
...
```
in your python code

**Comment by Salamek** [comment]
Well i take this as resolved, Closing
