### ISSUE TITLE
Error when trying to connect to B535-333

### ISSUE THREAD

**Issue by Wildside-UK** [Salamek/huawei-lte-api#122]
When trying to connect to a B535-333 I am presented with the following error. It seems that no Huawei monitor is able to connect to this router.

 Traceback (most recent call last):
   File "C:\Users\Steve\Documents\GitHub\huawei-lte-examples\huawei-lte-band\main.py", line 18, in <module>
     from huawei_lte_lib import *
   File "C:\Users\Steve\Documents\GitHub\huawei-lte-examples\huawei-lte-band\huawei_lte_lib.py", line 3, in <module>
     from huawei_lte_api.exceptions import ResponseErrorLoginCsfrException
 ImportError: cannot import name 'ResponseErrorLoginCsfrException' from 'huawei_lte_api.exceptions' (C:\Users\Steve\AppData\Local\Programs\Python\Python39\lib\site-packages\huawei_lte_api\exceptions.py)

**Comment by Salamek** [comment]
@Wildside-UK you need to use pre 1.5.3 version of `huawei-lte-api` or fix incorrect import in huawei-lte-examples.
Exception `ResponseErrorLoginCsfrException` has been deprecated for long time and was replaced by `ResponseErrorLoginCsrfException` in 1.5.3 release of `huawei-lte-api`
