### ISSUE TITLE
KeyError: 'ID' in _to_multi_basic_settings_ssid_body

### ISSUE THREAD

**Issue by Simoliv** [Salamek/huawei-lte-api#125]
Hi there, this great stuff, thanks a lot 1st !!

I was hoping to be able to switch off/on the wifi module of my B315s-22 4G Router, but it seems, there is some problem ? 

I did :

`from huawei_lte_api.Client import Client
from huawei_lte_api.Connection import Connection

with Connection('http://admin:XXXXXXXXXX@192.168.1.1/') as connection:
    client = Client(connection) 
    print(client.device.signal())  
    print("------")
    print(client.device.information())
    print("------")
    print(client.wlan.wifi_feature_switch())
    print("------")
    print(client.wlan.basic_settings())
    print("------")
    print(client.wlan.host_list())
    print("------")
    print(client.wlan.wifi_guest_network_switch(True))`

all but the last one work great, with the last command I get :

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    print(client.wlan.wifi_guest_network_switch(True))
  File "/srv/huawei-lte-api/huawei_lte_api/api/WLan.py", line 193, in wifi_guest_network_switch
    return self.set_multi_basic_settings(list(ssids))
  File "/srv/huawei-lte-api/huawei_lte_api/api/WLan.py", line 15, in _to_multi_basic_settings_ssid_body
    'ID': ssid['ID'],
KeyError: 'ID'

Can you check what this might be ? Can provide logs or whatever info you need.

best regards

**Comment by Salamek** [comment]
@Simoliv what does : 

```python
print(client.wlan.multi_basic_settings())
```
returns for you?

**Comment by Simoliv** [comment]
this : 

`{'WifiSsid': 'XXXXXXX', 'WifiChannel': '0', 'WifiHide': '0', 'WifiCode': 'ES', 'WifiMode': 'b/g/n', 'WifiRate': '0', 'WifiTxPwrPcnt': '100', 'WifiMaxAssoc': '32', 'WifiEnable': '1', 'WifiFrgThrshld': '2346', 'WifiRtsThrshld': '2347', 'WifiDtmIntvl': '1', 'WifiBcnIntvl': '100', 'WifiWme': '1', 'WifiPamode': '0', 'WifiIsolate': '0', 'WifiProtectionmode': '1', 'Wifioffenable': '1', 'Wifiofftime': '600', 'wifibandwidth': '0', 'wifiautocountryswitch': '0', 'wifiantennanum': '2', 'wifiguestofftime': '0', 'WifiRestart': '0'}
`

I found a solution in the meantime, I edited WLan.py commented some lines and removed an if condition, like this it works at the moment:

`def _to_multi_basic_settings_ssid_body(ssid: dict) -> dict:
    return {
        'Index': ssid['Index'],
        'WifiBroadcast': ssid['WifiBroadcast'],
        'wifiguestofftime': ssid['wifiguestofftime'],
        'WifiAuthmode': ssid['WifiAuthmode'],
        #'ID': ssid['ID'],
        'WifiEnable': ssid['WifiEnable'],
        #'wifiisguestnetwork': ssid['wifiisguestnetwork'],
        'WifiMac': ssid['WifiMac'],
        'WifiSsid': ssid['WifiSsid'],
        #'WifiRadiusKey': ssid['WifiRadiusKey'],
        'WifiWpaencryptionmodes': ssid['WifiWpaencryptionmodes'],
        'WifiWepKeyIndex': ssid['WifiWepKeyIndex'],
    }


def _set_wifi_enable(ssid: dict, status: bool) -> dict:
    #if ssid['wifiisguestnetwork'] == '0':
    #    return ssid

    if status:
        wifiEnable = '1'
    else:
        wifiEnable = '0'

    ssid['WifiEnable'] = wifiEnable
    return ssid
`

**Comment by Salamek** [comment]
@Simoliv nah, you just need to use correct multiline code syntax highlight block, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Also check if changes in https://github.com/Salamek/huawei-lte-api/commit/3e6a745c342cf20aed24ab99b7f44a0fe59b9f0a works for you
