### ISSUE TITLE
huawei  e3372h-320 not detected at all

### ISSUE THREAD

**Issue by elBoz73** [Salamek/huawei-lte-api#126]
Hello,
New to home assistant I would like to get sms notification (and maybe send command throw sms if possible).
But for now I am completly stuck on the first step which is getting my key recognized by home assistant... Bad start
The usb key should be compatible huawei  e3372h-320
From a pc everything is working fine, I tested the sms throw the web interface (and it si working).
I remove pin check and no password setup
I got the ip adress 192.168.8.1
But on home assistant the 3G key is not automaticaly recognize for integration ( tryed many usb ports)
and when I try to add it manually  I get a Time out .
Any idea on what I need to check or any logs I should activate (new at home assistant development level)

Thanks,

**Comment by Salamek** [comment]
Hi @elBoz73 this repository is not a part of home assistant project, so if you have any issues with their huawei-lte-api integration, you should reach them on their GitHub https://github.com/home-assistant/core or support forum if they have any...

Did you follow their huawei_lte integration howto wiki https://www.home-assistant.io/integrations/huawei_lte/ to set up your modem ?

**Comment by elBoz73** [comment]
Hi @Salamek,
Thanks, I tryed their wiki and it did not work.
I'll try to contact them on the core. 
in parallel of it, I will try to make it run on the operationg system

The key is not identified as USB ( I do no have any usb entry for it ).
I tried to directly install the api  using pip but I got the following error "ModuleNotFoundError: No module named 'distutils.cmd'
After I tried the wget but looks that we do not have access to the sodu command.
Any idea on how I could install your api?

Thanks.

**Comment by Salamek** [comment]
@elBoz73 USB huawei routers create a virtual network interface, check by running `ip addr` if it is created you should see something like:

```
5: enp0s20u10u1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether XXXX brd ff:ff:ff:ff:ff:ff
    inet 192.168.8.100/24 brd 192.168.8.255 scope global dynamic noprefixroute enp0s20u10u1
       valid_lft 86400sec preferred_lft 86400sec
    inet6 XXXXX/64 scope link tentative noprefixroute 
       valid_lft forever preferred_lft forever
```
added to the interface list after connecting the USB key

**Comment by elBoz73** [comment]
@Salamek, the ip command does not seems to be installed on home assistant operating system. 
Maybe I missed something, so I'll try to get deeper in this. I keep you inform.
