### ISSUE TITLE
Exception has occurred: SSLError

### ISSUE THREAD

**Issue by ryanbarlow97** [Salamek/huawei-lte-api#127]
![image](https://user-images.githubusercontent.com/7389646/154159716-45370cf4-5832-4efe-bc39-b9c16dd8db47.png)

**Comment by ryanbarlow97** [comment]
![image](https://user-images.githubusercontent.com/7389646/154159793-aca0052a-d89d-4cfd-86a0-db786ab3151d.png)

I have been trying to "update" my certificate but I can't seem to do it. I don't really know what else to do?

**Comment by Salamek** [comment]
@ryanbarlow97 In that case, you need to ignore SSL, see this example:

https://github.com/Salamek/huawei-lte-api/blob/fdfcedd72fa5b5fcf1fe50857d20eca045839666/examples/ignore_ssl_check.py#L21-L33

**Comment by ryanbarlow97** [comment]
Alright, thanks, I sorta fixed it by just rewriting the API without realising this was a thing. Would it be possible to use this API to change bands?

**Comment by Salamek** [comment]
@ryanbarlow97 see
*  `DialUp.set_default_profile`
*  `DialUp.delete_profile`
*  `DialUp.create_profile`

**Comment by ryanbarlow97** [comment]
> 
This doesn't let me change bands, I want to set it so my router will only look at bands 1, 20, and 28.

Thanks

**Comment by Salamek** [comment]
@ryanbarlow97 ah band, sorry i read profile for some reason lol,see:

https://github.com/Salamek/huawei-lte-api/blob/fdfcedd72fa5b5fcf1fe50857d20eca045839666/huawei_lte_api/api/Net.py#L16
