### ISSUE TITLE
KeyError: 'password_type' on E5776s-32

### ISSUE THREAD

**Issue by drhaka** [Salamek/huawei-lte-api#129]
pi@raspberrypi:~$ python3 -i device_info.py http://admin:admin@192.168.42.1/
Traceback (most recent call last):
  File "/home/pi/device_info.py", line 19, in <module>
    with Connection(args.url, username=args.username, password=args.password) as connection:
  File "/home/pi/.local/lib/python3.9/site-packages/huawei_lte_api/Connection.py", line 28, in __init__
    self.user_session = UserSession(self, username, password) if username else None
  File "/home/pi/.local/lib/python3.9/site-packages/huawei_lte_api/api/User.py", line 25, in __init__
    self.user.login(username, password, True)
  File "/home/pi/.local/lib/python3.9/site-packages/huawei_lte_api/api/User.py", line 109, in login
    return self._login(username, password, PasswordTypeEnum(int(state_login['password_type'])))
KeyError: 'password_type'
>>>

**Comment by Salamek** [comment]
Hmm looks like your modem is not returning correct data from `state_login`
What do you get when running

```python
from huawei_lte_api.Client import Client
from huawei_lte_api.Connection import Connection
with Connection('http://192.168.42.1/') as connection:
    client = Client(connection)
    print(client.user.state_login())
```

?

**Comment by drhaka** [comment]
It returns

{'State': '-1', 'Username': None}

Den sön 27 feb. 2022 kl 16:28 skrev Adam Schubert ***@***.***

**Comment by Salamek** [comment]
Ok so `password_type` is missing, that's new...

Can you try to replace this line in your install of `huawei_lte_api`
https://github.com/Salamek/huawei-lte-api/blob/fdfcedd72fa5b5fcf1fe50857d20eca045839666/huawei_lte_api/api/User.py#L109

With 
```python
return self._login(username, password, PasswordTypeEnum.BASE_64)
```
That forces Password type to BASE_64

if that does not work, try to use

```python
return self._login(username, password, PasswordTypeEnum.SHA256)
```

if none of these work, you will need to reveng your `webgui`  login logic (or downloading those js files and sending them to me somehow, so i can reveng it)

**Comment by drhaka** [comment]
That got me past the initial error, however with both options I still end
up with
 huawei_lte_api.exceptions.ResponseErrorException: 100008: Unknown

however if I remove the username:password and use limited access I now get
some results

print(client.device.signal()) returns
100002: No support

print(client.device.information()) returns
{'DeviceName': 'E5776', 'SerialNumber': 'redacted', 'Imei': 'redacted',
'Imsi': 'redacted', 'Iccid': 'redacted', 'Msisdn': 'redacted',
'HardwareVersion': 'CL2E5776SM', 'SoftwareVersion': '21.202.15.00.1102',
'WebUIVersion': '12.003.03.01.03', 'MacAddress1': 'redacted',
'MacAddress2': None, 'ProductFamily': 'LTE', 'Classify': 'DataCard'}

Here's how to log in:

curl 'http://192.168.42.1/api/user/login' \
  -H 'Connection: keep-alive' \
  -H 'Accept: */*' \
  -H 'DNT: 1' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36' \
  -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'Origin: http://192.168.42.1' \
  -H 'Referer: http://192.168.42.1/html/home.html' \
  -H 'Accept-Language: sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7,nb;q=0.6' \
  --data-raw '<?xml version="1.0"
encoding="UTF-8"?><request><Username>admin</Username><Password>YWRtaW4=</Password></request>'
\
  --compressed \
  --insecure

<?xml version="1.0" encoding="UTF-8"?><response>OK</response>

curl 'http://192.168.42.1/api/user/state-login' \
  -H 'Connection: keep-alive' \
  -H 'Accept: */*' \
  -H 'DNT: 1' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36' \
  -H 'Referer: http://192.168.42.1/html/home.html' \
  -H 'Accept-Language: sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7,nb;q=0.6' \
  --compressed \
  --insecure

<?xml version="1.0" encoding="UTF-8"?><response>OK</response>

and then fetch some information

curl 'http://192.168.42.1/api/wlan/security-settings' \
  -H 'Connection: keep-alive' \
  -H 'Accept: */*' \
  -H 'DNT: 1' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36' \
  -H 'Referer: http://192.168.42.1/html/quicksetup.html' \
  -H 'Accept-Language: sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7,nb;q=0.6' \
  --compressed \
  --insecure

<?xml version="1.0" encoding="UTF-8"?>
<response>
<WifiAuthmode>WPA-PSK</WifiAuthmode>
<WifiBasicencryptionmodes>NONE</WifiBasicencryptionmodes>
<WifiWpaencryptionmodes>MIX</WifiWpaencryptionmodes>
<WifiWepKey1>12345</WifiWepKey1>
<WifiWepKey2>12345</WifiWepKey2>
<WifiWepKey3>12345</WifiWepKey3>
<WifiWepKey4>12345</WifiWepKey4>
<WifiWepKeyIndex>1</WifiWepKeyIndex>
<WifiWpapsk>redacted</WifiWpapsk>
<WifiWpsenbl>1</WifiWpsenbl>
<WifiWpscfg>0</WifiWpscfg>
<WifiRestart>0</WifiRestart>
</response>

Let me know if there's any other information that would be helpful.

Den sön 27 feb. 2022 kl 16:28 skrev Adam Schubert ***@***.***

**Comment by Salamek** [comment]
So `PasswordTypeEnum.BASE_64` works for you? (looks like YWRtaW4= is  just base64 `admin`) If so, ill make it default when no `password_type` is set and we can go from there

**Comment by Salamek** [comment]
@drhaka ping

**Comment by drhaka** [comment]
Well not really, User.py still exits due to 100008: Unknown if i try to
connect with any credentials. I could only get unprivileged to work now
with the fix. But it's something.

The login I did through curl timed out after half a minute or so, but
main.js has a function that seems to be what's keeping the session from
timing out when in the browser:

function postHeartBeatRequest()
{
    var Keep = {
        keep: 1
    };
    var submitData = object2xml('request', Keep);
    saveAjaxData('api/user/session', submitData, function($xml) {
    });
}

As far as I can tell, this is the only session handling there is, but I
could send you the entire main.js and home.js if you'd like.

Den tis 1 mars 2022 kl 11:29 skrev Adam Schubert ***@***.***>:

**Comment by Salamek** [comment]
Ok i have modified master to use BASE_64 password when `password_type` is not provided, and for the rest you can send those *.js files to my email (in bio)

**Comment by Salamek** [comment]
No response since my change, i consider this as fixed, closing...
