### ISSUE TITLE
Delete all messages from LocalOutbox

### ISSUE THREAD

**Issue by GG575** [Salamek/huawei-lte-api#130]
How do I delete all messages in LocalOutbox?

**Comment by Salamek** [comment]
See https://github.com/Salamek/huawei-lte-api/blob/master/huawei_lte_api/api/Sms.py

https://github.com/Salamek/huawei-lte-api/blob/fdfcedd72fa5b5fcf1fe50857d20eca045839666/huawei_lte_api/api/Sms.py#L26
https://github.com/Salamek/huawei-lte-api/blob/fdfcedd72fa5b5fcf1fe50857d20eca045839666/huawei_lte_api/api/Sms.py#L44

**Comment by GG575** [comment]
Am reusit. Multumesc pentru ajutor.

**Comment by GG575** [comment]
I succeeded. Thank you for help.

**Comment by albebert** [comment]
@GG575 can you share your code please ? i'm not good at python, and need to do the same. Thanks in advance
