### ISSUE TITLE
Version called 1.6 on GitHub but 1.6.0 on PyPI

### ISSUE THREAD

**Issue by dotlambda** [Salamek/huawei-lte-api#135]

**Comment by Salamek** [comment]
@dotlambda  and that is problem why exactly?

In my world 1.6 == 1.6.0:

```python
from packaging import version


one_dot_six = version.Version('1.6')
one_dot_six_dot_zero = version.Version('1.6.0')
one_dot_five_dot_nine = version.Version('1.5.9')

if one_dot_six == one_dot_six_dot_zero:
    print('It\'s fine!')

if one_dot_six > one_dot_five_dot_nine:
    print('Really, it\'s fine!')

if one_dot_six_dot_zero > one_dot_five_dot_nine:
    print('Oh c\'mon!')
```

```bash
python t.py
It's fine!
Really, it's fine!
Oh c'mon!
```

But if that creates some issues somewhere  (some packaging systems or idk) i can release a patch version for you (1.6.1)  and change version generator in https://github.com/Salamek/version to include zero patch version

**Comment by dotlambda** [comment]
I'm not sure it actually creates an issue. I just wanted to make you aware of te discrepancy.
