### ISSUE TITLE
Receiving SMS and based on the content take further action

### ISSUE THREAD

**Issue by BenjaminKnol** [Salamek/huawei-lte-api#14]
I am trying to use your software to detect whenever an sms is received that tells me that I have 500MB left of my data package so I can send a new SMS which gives me an extra gig of data. I think this api is right for that but can't figure out how to acces the content of received SMS' so that I can do a simple 
if(message.contains("message telling me I'm nearly out of data")){
  send_sms(foo, bar, etc)
}else{
   console.log(message) //since no other messages will probably be received through SMS.
}

Am I on the right track or am I totally missing the point?

**Comment by Salamek** [comment]
@BenjaminKnol 
Well theoretically yes, practically:
```python
from huawei_lte_api.Client import Client
from huawei_lte_api.AuthorizedConnection import AuthorizedConnection

# Create connection to modem
connection = AuthorizedConnection('http://admin:MY_SUPER_TRUPER_PASSWORD@192.168.8.1/')

# Get client
client = Client(connection)

# Get list of received sms, i'm not sure how returned data of this call look, so this needs some testing
for sms in client.sms.get_sms_list():
    # Check if message is expected message etc.
    if sms.message == 'expected_content' and sms.phone_number == 'expected_sender':
        # If it is expected message, react on it by sending SMS, we need to check status of send_sms, again i don't know return data of this call, so it needs some testing
        if client.sms.send_sms('PHONE_NUMBER', 'SMS_MESSAGE')['send'] == 'ok':
            # We sent our SMS successfully, lets delete old message we was reacting on, this again needs some testing
            client.sms.delete_sms([sms.id])
```
This code example is using correct methods etc, but idk return data format of these methods and i don't have any Huawei modem in my possession right now... so i'm unable to test it...
So you should check output of each method to see what it is returning (print(client.sms.get_sms_list())) etc

**Comment by BenjaminKnol** [comment]
right now I've got the following code:
for sms in client.sms.get_sms_list():
    (sms)

it is spitting out the following error:
Traceback (most recent call last):
  File "/Users/DennisK/Desktop/BenBot/huawei-lte-api/Run.py", line 16, in <module>
    for sms in client.sms.get_sms_list():
  File "/Users/DennisK/Desktop/BenBot/huawei-lte-api/huawei_lte_api/AuthorizedConnection.py", line 19, in wrapped
    return fn(*args, **kw)
  File "/Users/DennisK/Desktop/BenBot/huawei-lte-api/huawei_lte_api/api/Sms.py", line 41, in get_sms_list
    ('UnreadPreferred', unread_preferred),
  File "/Users/DennisK/Desktop/BenBot/huawei-lte-api/huawei_lte_api/Connection.py", line 112, in post
    data = self._check_response_status(self._process_response_xml(response.content))
  File "/Users/DennisK/Desktop/BenBot/huawei-lte-api/huawei_lte_api/Connection.py", line 64, in _check_response_status
    error_code
huawei_lte_api.exceptions.ResponseErrorException: 100005: Unknown

So apperently I'm calling upon things that don't exist or am I reading this error wrong?

**Comment by Salamek** [comment]
@BenjaminKnol What modem do you have ?

**Comment by BenjaminKnol** [comment]
@Salamek  B525s-23a. So to clarify myself, in case you found my other messages a bit confusing, What I'm trying to achieve is to get the latest received message or get an update whenever the modem receives a message. Then I want (when the message is telling me that I have 500 MB left over) to send a message which asks for another gig. If the message is different I just want to sleep for 10 minutes.(otherwise I would spam the modem with requests no?) It may even be an option to just check the latest message as I get a confirmation when requesting a new gig.

**Comment by BenjaminKnol** [comment]
@Salamek It would probably be best to just check the last received SMS every 10-15 mins so I guess my question would be wether itis possible to just check the last received SMS for its content. Then I'd probably put that in a String and then check wether that String contains the message telling me that I'm running low on data

**Comment by Salamek** [comment]
@BenjaminKnol calling `client.sms.get_sms_list()` is a correct way, there is no "get_last_sms" call...
When `client.sms.get_sms_list()` is not working for you... you are on your own in debuging what is going on...since i dont own any device i can test this on.
Support for `B525s-23a` was added by @scop , so maybe ask him for help/test? maybe ?

**Comment by BenjaminKnol** [comment]
@scop I'm trying to create a system where whenever I receive an SMS telling me I have only 500MB left on my 'unlimited' data package, I send an SMS through the modem to a certain number with a short String that ask for another GB. I've got the code for sending an SMS and that works perfectly. I'm able to ask for 1 GB or even more if I write a simple for loop and just send the message multiple times. The thing that I'm getting stuck on is the following:

I'm trying to get the latest received SMS and then I want to do an 'if' asking if the content of this message contains a string. if it matches the string I ask for another GB if it doesn't I want to wait 10-15 min and then try again.

Also I would like to wish both you @scop and @Salamek a very merry christmas.

**Comment by Salamek** [comment]
@BenjaminKnol there are some fixes in master branch by @scop, can you retest your code with latest master ?

**Comment by Salamek** [comment]
@BenjaminKnol is this issue resolved for you ?

**Comment by Salamek** [comment]
No response for 2 days, i take this as resolved...

**Comment by BenjaminKnol** [comment]
So sorry I couldnt response I was offline for a few days. The update to the master did fix my problem and I got it working brilliantly. Many thanks!
