### ISSUE TITLE
Reboot script

### ISSUE THREAD

**Issue by mihairotaru** [Salamek/huawei-lte-api#161]
Hi, 

Is there a reboot script please? I need it for a Huawei B535-333. I currently use this reboot script for Huawei B525:

https://github.com/jinxo13/HuaweiB525Router/blob/master/reboot.py

Thanks,
Mihai

**Comment by Salamek** [comment]
See https://github.com/Salamek/huawei-lte-api/blob/master/examples/reconnect_dialup.py
