### ISSUE TITLE
Switch Wifi on/off

### ISSUE THREAD

**Issue by colpomatteo** [Salamek/huawei-lte-api#162]
Hi, is there a script for switch wifi on/off? I need it for B535-232.

Thanks ;)

**Comment by Salamek** [comment]
See https://github.com/Salamek/huawei-lte-api/blob/master/huawei_lte_api/api/WLan.py

`wifi_guest_network_switch` is used to toggle guest wifi, just copy and modify that code to toggle wifi with specific ssid...

**Comment by colpomatteo** [comment]
Thank you.
I tried but If I call wifi_guest_network_switch as it is, it returns 'Request format error', if I try to use it with my wifi ssid it returns '100006: Unknown'. ‾\\\_(\*-\*)\_/‾

My code: 
```
def _set_wifi_enable(ssid: dict, status: bool) -> dict:
    if ssid.get('WifiSsid') != "myssid":
        return ssid

    ssid['WifiEnable'] = '1' if status else '0'
    return ssid
```

**Comment by Salamek** [comment]
@colpomatteo check version 1.6.8, i have added a method to disable/enable wifi,
see this example https://github.com/Salamek/huawei-lte-api/blob/master/examples/toggle_wifi.py
