### ISSUE TITLE
Include change log / release notes

### ISSUE THREAD

**Issue by scop** [Salamek/huawei-lte-api#20]
Some kind of change log or release notes for releases would be nice. Maybe https://github.com/apps/release-drafter would be useful? I have no experience with it myself, the Home Assistant folks just recommended it in https://github.com/home-assistant/home-assistant/pull/19987.

**Comment by Salamek** [comment]
@scop release-drafter is nice piece of SW, but im using differend release workflow (https://github.com/Salamek/version)
So i will try to fill some News/Fixes info in each release since version 1.1.4
