### ISSUE TITLE
E3372 CL1E3372SM Ver.A api doesn't work

### ISSUE THREAD

**Issue by jeremyruffer** [Salamek/huawei-lte-api#206]
I have downloaded the latest version but it requires python 3.7 and I only have 3.6.

Is it possible to obtain a version that works with Python 3.6.8?

Regards

Jeremy

**Comment by jeremyruffer** [comment]
You are probably right but I don't think it would have helped.

There is a major difference in the api for the model I am using. 

/api/webserver/SesTokInfo does not exist but api/webserver/token does. send_sms needs it but functions like signal, sms-count and send-status don't.

**Comment by Salamek** [comment]
`/api/webserver/SesTokInfo` and `api/webserver/token` are ~interchangeable

**Comment by jeremyruffer** [comment]
Thank you for responding.
