### ISSUE TITLE
Unlock PIN Method Returns `101006 Unknown Error` and Fails to Unlock PIN on Modem

### ISSUE THREAD

**Issue by NaturalT314** [Salamek/huawei-lte-api#223]
## **Description:**
I'm encountering an issue with the unlock PIN method on my modem. The method returns the error `101006 Unknown Error`, and it fails to unlock the PIN. This problem occurs consistently, and I haven't been able to successfully unlock the PIN.

## **Device Details:**

-   **Device Name:** E3372
-   **Serial Number:** G4PDU16111002102
-   **IMEI:** 869907022856435
-   **Hardware Version:** CL2E3372HM
-   **Software Version:** 22.323.01.00.00
-   **Web UI Version:** 17.100.13.01.03-Mod1.10

## **Steps to Reproduce:**

1.  Lock the PIN manually.
2.  Attempt to unlock the PIN using the relevant method.
3.  The method returns the error code `101006 Unknown Error`.
4.  The PIN remains locked.

## **Expected Behavior:**

The PIN should unlock successfully without returning an error.

## **Actual Behavior:**

The method returns an error, and the PIN is not unlocked.

**Comment by Salamek** [comment]
Fixed by #224, released in 1.10
