### ISSUE TITLE
Running on RaspberryPI and getting a seemingly randomized object from client.sms.get_sms_list

### ISSUE THREAD

**Issue by BenjaminKnol** [Salamek/huawei-lte-api#23]
Hey there, it's me again running into another problem! So I got the API to work brilliantly on my laptop but for convenience I'm now trying to run it on a raspberry PI for the purpose of sending an SMS to ask for extra GB's when I'm running low to my ISP. Like I said I got it to work perfectly on my laptop so I just pushed that code to a fork and then pulled that to my PI. First ran into a spot of bother because I hardly ever work with Python where I tried installing the required modules but used pip install causing me to install them for python 2.7 (dumb mistake I know, but I'm telling you this so you realize that this problem is probably a mistake on my side.)

The problem that I'm having is that when I run the following code:
`from huawei_lte_api.Client import Client
from huawei_lte_api.AuthorizedConnection import AuthorizedConnection
from huawei_lte_api.Connection import Connection
from huawei_lte_api.api.Sms import Sms
import sched, time
s = sched.scheduler(time.time, time.sleep)

def ask_extra_gigs(sc):
    connection = AuthorizedConnection('http://admin:xxxx@192.168.8.1/')
    client = Client(connection) # This just simplifies access to separate API groups, you can use device = Device(connection) if you want
    latest_sms = str(list(list(client.sms.get_sms_list()["Messages"].values())[0][0].values())[3])
    print(latest_sms)
    if '500MB' in latest_sms:
        print('asking for data')
        for _ in range(0, 5):
            client.sms.send_sms([1280], "1GB EXTRA")
        s.enter(600, 1, ask_extra_gigs, (sc,))
    elif 'Gelukt!' in latest_sms:
        print('plenty of data left')
        s.enter(600, 1, ask_extra_gigs, (sc,))
    else:
        print('unexpected message')

s.enter(1, 1, ask_extra_gigs, (s,))
s.run()`
    latest_sms = str(list(list(client.sms.get_sms_list()["Messages"].values())[0][0].values())[3]) this line doesn't give me the content of the latest message anymore (like it did on my windows laptop) but instead it gives one of several different options. I've come to realize that list(client.sms.get_sms_list()["Messages"].values())[0][0] can give me all the information about the latest sms in an incredibly random order.

Is this a unix problem or something? I truly have no clue, the way I see it it shouldn't care whether it is run on windows or unix based OS.

Any help is greatly appreciated

**Comment by BenjaminKnol** [comment]
NVM, I was (and stil am) a dumbass when writing the original code. Because instead of looking through a key value list (think it's called an object not sure (once again not that familiar with Python)) I first remove the keys and then chose one from the returned array... Now I've changed it to the sensible option where it just looks for the key "Content" you know like a sane person would. Woops

Anyway I'm still interested why I'd get a randomized list. So I now change my stupidity into a scientific question namely: "Why do I get random?". So if anyone has a clue please do respond.

**Comment by Salamek** [comment]
@BenjaminKnol maybe enable SMS sorting ? There is none by default...
You have these options to sort it:
```
sort_type: int=0,
ascending: int=0,
unread_preferred: int=0
```

I forgot to create Sms.SortTypeEnum, so if you colud parse those values from web GUI and post them here so i can add them. 
You want to sort by receive date descending and maybe unread_preferred too ?
Something ~like:
```
get_sms_list(
    sort_type=?,
    ascending=0,
    unread_preferred=1
)
```

**Comment by BenjaminKnol** [comment]
If I can find the time I may consider it but don't expect too much since I'm quite busy currently.

**Comment by Salamek** [comment]
Closed due to old age
