### ISSUE TITLE
Device.control() info please

### ISSUE THREAD

**Issue by ahlstart** [Salamek/huawei-lte-api#33]
Hi,

I saw a method (set_control) which calls Device.control with 4 as default argument. I also saw value 1 as the way to reboot the router. My watchdog program currently reboots my router when it notices that no bytes have been received during the last monitoring interval, but as the router also performs switch duties in the local LAN, I would actually like to just disconnect it from LTE and then reconnect. So, what does device.control(4) do, and how can I disconnect and reconnect the router to my mobile internet provider?

**Comment by ahlstart** [comment]
I traced the traffic and found that the admin page sent a POST request to http: // 192.168.8.1 /api/dialup/mobile-dataswitch , with payload <?xml version="1.0" encoding="UTF-8"?><request><dataswitch>1</dataswitch></request> for reconnecting.

So, my monitoring program needs to call 
client.dial_up.set_mobile_dataswitch(0)
to disconnect and the same with parameter 1 to reconnect.
Seems to work fine.

Thanks!

**Comment by Salamek** [comment]
@ahlstart FYI i added this info to function comment
https://github.com/Salamek/huawei-lte-api/blob/2e07d93482c0a390669b9294962f72bb7af4220f/huawei_lte_api/api/DialUp.py#L32

THX for info!
