### ISSUE TITLE
Delete all SMS

### ISSUE THREAD

**Issue by QuinnDD** [Salamek/huawei-lte-api#34]
Hi, im trying to delete all messages after I did something with the received messages, but I get the error unknown 10005. any help?

**Comment by Steve-Temple** [comment]
I had this problem (with a B525). After a little digging, it appears that the Huawei API for SMS delete needs a single "Index", not a list. I modified "delete_sms" in "huawei_lte_api/api/Sms.py" to take a single argument and this seemed to fix it...

```
   def delete_sms(self, sms_id: int):
        return self._connection.post('sms/delete-sms', {'Index': sms_id})

```
Regards, Steve`

**Comment by Salamek** [comment]
Can someone confirm if this is true for other modems too ?

**Comment by robertliska** [comment]
I confirm the Steve's fix works also for E3372. (list not working)

**Comment by cagnulein** [comment]
I confirm the Steve's fix works for B525
