### ISSUE TITLE
Remove @autohorized_call enforcement

### ISSUE THREAD

**Issue by scop** [Salamek/huawei-lte-api#36]
Whether some method requires authentication or not varies between devices, and I suspect even between firmware revisions. The `@authorized_call` decorators may result in some methods not even being tried with unauthorized connections, even if they would work just fine.

I'm not fully aware of the reasoning/need for the decorator or the enforcement in the first place, so not submitting a PR. But I think it would good at least if there was no `AuthorizedConnection` enforcement in effect at all -- if a method that requires authorization is attempted, it'll just raise a `ResponseErrorLoginRequiredException` which is just fine. Perhaps just change the decorator to do `enforce_authorized_connection` only if there is an `AuthorizedConnection` there, and do nothing if not.

**Comment by Salamek** [comment]
@scop `@authorized_call` was created to save request (And i think some endpoints was crashing with differend error when not authorized, but idk) to modem, but if this behavior is differend for differend modems, than `@authorized_call` is useless and we can drop it.

But would be good to mention authorization requirement in method comment, something like:

```python
def something(self, foo):
    """
    Do something, Requires authorization for: B310s-22, B525s-23a
   :param foo: Foo 
    """
```

For modems we are sure about this OFC...

And i was thinking about merging `AuthorizedConnection` with `Connection`...?

**Comment by scop** [comment]
At least these methods have mixed auth/not required between devices:
- client.net.network
- client.online_update.configuration
- client.wlan.status_switch_settings
- client.wlan.wps_pbc

There are also quite a few (about two dozen or so) methods already that are lacking the authorized_call decorator, but require auth at least with some devices.

I think merging the two connections would be fine; just don't do auth if no username or pass was supplied.

It would be nice somehow to avoid logging in as much as possible, because of the devices' problems with handling multiple sessions. For example I've seen a continuously active huawei_lte_api connection preventing logging in from the web UI altogether. Not sure if this sanely solvable at all though. Perhaps something like "try without auth and session first, if it gives a 100003, then retry with auth if there is a session or username/pass are available (and in that case do a login)". That wouldn't be too efficient though.

Wrt documenting device models and their auth requirements, I can share my knowledge, but I'm afraid (guessing, no hard evidence) that the differences wouldn't be limited to device models but also firmware versions :/

**Comment by Salamek** [comment]
@scop 

> There are also quite a few (about two dozen or so) methods already that are lacking the authorized_call decorator, but require auth at least with some devices.

Well... lets just drop @autohorized_call and related code

> It would be nice somehow to avoid logging in as much as possible, because of the devices' problems with handling multiple sessions. For example I've seen a continuously active huawei_lte_api connection preventing logging in from the web UI altogether. Not sure if this sanely solvable at all though. 

I dont think that there is anything sane we can do about this... just mention in DOC that this may happen.

> Perhaps something like "try without auth and session first, if it gives a 100003, then retry with auth if there is a session or username/pass are available (and in that case do a login)". That wouldn't be too efficient though.

I feel like this is too complex to be implemented in this library and some ppl may not like it, i would rather let users of this library handle this as they want (they can always catch a Exception and act on it) but we may provide some code examples implementing this on top of this library.

> Wrt documenting device models and their auth requirements, I can share my knowledge, but I'm afraid (guessing, no hard evidence) that the differences wouldn't be limited to device models but also firmware versions :/

In that case, lets just not do that, it would be wasted time :+1:

**Comment by scop** [comment]
Cool :+1:
