### ISSUE TITLE
net.network() auth issue

### ISSUE THREAD

**Issue by cagnulein** [Salamek/huawei-lte-api#39]
Hi, i'm using your lib every day, thanks for your work!
I've encountered a strange issue about client.net.network().
As you can see from the script below, the client.device.information() works so the authentication process is ok, but when i try to print the net.network() it gives me an error. What do you think?

from huawei_lte_api.Client import Client
from huawei_lte_api.AuthorizedConnection import AuthorizedConnection
from huawei_lte_api.Connection import Connection
from huawei_lte_api.api.Net import Net

connection = AuthorizedConnection('http://admin:PASSWORD@192.168.0.254/')
client = Client(connection)
signal = client.device.signal()
print(client.device.information())
info = client.device.information()

net = Net(connection)
print(client.net.network())
print(client.net.register())

`{'Msisdn': 'XXXX', 'submask': '255.255.255.255', 'workmode': 'LTE', 'WebUIVersion': '21.100.44.00.03', 'SoftwareVersion': '11.189.61.00.1217', 'Imsi': 'XXXX', 'MacAddress2': None, 'HardwareVersion': 'WL1B520FM', 'wan_dns_address': 'XXXX', 'WanIPv6Address': None, 'Iccid': 'XXX', 'DeviceName': 'B525s-23a', 'wan_ipv6_dns_address': None, 'supportmode': 'LTE|WCDMA|GSM', 'Imei': 'XXXX', 'Classify': 'cpe', 'WanIPAddress': '10.225.163.102', 'SerialNumber': 'XXXX', 'ProductFamily': 'LTE', 'MacAddress1': 'XXXXXX'}
Traceback (most recent call last):
  File "router.py", line 19, in <module>
    print(client.net.network())
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/AuthorizedConnection.py", line 20, in wrapped
    return fn(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/api/Net.py", line 15, in network
    return self._connection.get('net/network')
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/Connection.py", line 137, in get
    return self._check_response_status(self._process_response_xml(response.content))
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/Connection.py", line 37, in _process_response_xml
    return xmltodict.parse(xml, dict_constructor=dict)
  File "/usr/local/lib/python3.5/dist-packages/xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
`

**Comment by Salamek** [comment]
@cagnulein only thing i can say from this is that XML parser failed to parse response from your router for some reason, does your router support this method ? are you calling it correctly ?

**Comment by cagnulein** [comment]
I don't know, how can i check if the B525s-23a supports it? What do you mean by "calling it correctly"? The method is parameterless so i can't do it wrong, isn't it?
Thanks

**Comment by Salamek** [comment]
@cagnulein hmm looks like your router should support this... sadly i dont have any device here to test what is going on on my side...

Hmm could u put `print(response.content)` on https://github.com/Salamek/huawei-lte-api/blob/e9f9a844e26209dbd6e22fe8119d4218848188b7/huawei_lte_api/Connection.py#L160 ? 

Run it again and put output here ? 

(That also reminds me i shoud add some _LOGGER.debug() into request/response calls)

**Comment by cagnulein** [comment]
Sure!
`
b'<?xml version="1.0" encoding="UTF-8"?><response><username></username><password_type>4</password_type><firstlogin>1</firstlogin><history_login_flag>0</history_login_flag><wifipwdsamewithwebpwd>1</wifipwdsamewithwebpwd><extern_password_type>1</extern_password_type><State>-1</State><userlevel></userlevel></response>'
b'<?xml version="1.0" encoding="UTF-8"?>\r\n<response>\r\n<pci>124</pci>\r\n<sc></sc>\r\n<cell_id>205597482</cell_id>\r\n<rsrq>-12dB</rsrq>\r\n<rsrp>-114dBm</rsrp>\r\n<rssi>-81dBm</rssi>\r\n<sinr>4dB</sinr>\r\n<rscp></rscp>\r\n<ecio></ecio>\r\n<mode>7</mode>\r\n<ulbandwidth>20MHz</ulbandwidth>\r\n<dlbandwidth>20MHz</dlbandwidth>\r\n<txpower>PPusch:15dBm PPucch:19dBm PSrs:0dBm PPrach:23dBm</txpower>\r\n<tdd></tdd>\r\n<ul_mcs>mcsUpCarrier1:6</ul_mcs>\r\n<dl_mcs>mcsDownCarrier1Code0:14 mcsDownCarrier1Code1:15 </dl_mcs>\r\n<earfcn>DL:1350 UL:19350</earfcn>\r\n<rrc_status>1</rrc_status>\r\n<rac></rac>\r\n<lac></lac>\r\n<tac>18306</tac>\r\n<band>3</band>\r\n<nei_cellid>No1:0</nei_cellid>\r\n<plmn>22201</plmn>\r\n<ims>0</ims>\r\n</response>\r\n'
b'<?xml version="1.0" encoding="UTF-8"?>\r\n<response>\r\n<DeviceName>B525s-23a</DeviceName>\r\n<SerialNumber>XXXXXXX</SerialNumber>\r\n<Imei>XXXXX</Imei>\r\n<Imsi>XXXXXX</Imsi>\r\n<Iccid>XXXX</Iccid>\r\n<Msisdn>XXXXX</Msisdn>\r\n<HardwareVersion>WL1B520FM</HardwareVersion>\r\n<SoftwareVersion>11.189.61.00.1217</SoftwareVersion>\r\n<WebUIVersion>21.100.44.00.03</WebUIVersion>\r\n<MacAddress1>XXXXX</MacAddress1>\r\n<MacAddress2></MacAddress2>\r\n<WanIPAddress>10.246.77.214</WanIPAddress>\r\n<wan_dns_address>213.213.33.107,89.118.249.7</wan_dns_address>\r\n<WanIPv6Address></WanIPv6Address>\r\n<wan_ipv6_dns_address></wan_ipv6_dns_address>\r\n<ProductFamily>LTE</ProductFamily>\r\n<Classify>cpe</Classify>\r\n<supportmode>LTE|WCDMA|GSM</supportmode>\r\n<workmode>LTE</workmode>\r\n<submask>255.255.255.255</submask>\r\n</response>\r\n'
{'WanIPAddress': '10.246.77.214', 'SerialNumber': 'XXXX', 'Msisdn': 'XXXX', 'SoftwareVersion': '11.189.61.00.1217', 'Imsi': 'XXXX', 'MacAddress2': None, 'Classify': 'cpe', 'workmode': 'LTE', 'DeviceName': 'B525s-23a', 'submask': '255.255.255.255', 'HardwareVersion': 'WL1B520FM', 'WanIPv6Address': None, 'supportmode': 'LTE|WCDMA|GSM', 'ProductFamily': 'LTE', 'MacAddress1': 'XXXX', 'wan_dns_address': '213.213.33.107,89.118.249.7', 'Iccid': 'XXXX', 'wan_ipv6_dns_address': None, 'WebUIVersion': '21.100.44.00.03', 'Imei': 'XXXX'}
b'<?xml version="1.0" encoding="UTF-8"?>\r\n<response>\r\n<DeviceName>B525s-23a</DeviceName>\r\n<SerialNumber>XXXX</SerialNumber>\r\n<Imei>XXXX</Imei>\r\n<Imsi>XXXX</Imsi>\r\n<Iccid>XXXX</Iccid>\r\n<Msisdn>XXXX</Msisdn>\r\n<HardwareVersion>WL1B520FM</HardwareVersion>\r\n<SoftwareVersion>11.189.61.00.1217</SoftwareVersion>\r\n<WebUIVersion>21.100.44.00.03</WebUIVersion>\r\n<MacAddress1>XXXX</MacAddress1>\r\n<MacAddress2></MacAddress2>\r\n<WanIPAddress>10.246.77.214</WanIPAddress>\r\n<wan_dns_address>213.213.33.107,89.118.249.7</wan_dns_address>\r\n<WanIPv6Address></WanIPv6Address>\r\n<wan_ipv6_dns_address></wan_ipv6_dns_address>\r\n<ProductFamily>LTE</ProductFamily>\r\n<Classify>cpe</Classify>\r\n<supportmode>LTE|WCDMA|GSM</supportmode>\r\n<workmode>LTE</workmode>\r\n<submask>255.255.255.255</submask>\r\n</response>\r\n'
b''
Traceback (most recent call last):
  File "router.py", line 19, in <module>
    print(client.net.network())
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/AuthorizedConnection.py", line 20, in wrapped
    return fn(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/api/Net.py", line 15, in network
    return self._connection.get('net/network')
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/Connection.py", line 137, in get
    return self._check_response_status(self._process_response_xml(response.content))
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/Connection.py", line 37, in _process_response_xml
    return xmltodict.parse(xml, dict_constructor=dict)
  File "/usr/local/lib/python3.5/dist-packages/xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
`

**Comment by Salamek** [comment]
@cagnulein from data you are  provided, it looks like your device is returning b'' (empty string) on `client.net.network()` call and that is not correct... 
You could look on requests made by your modem admin interface via chromium dev tools and check if your modem supports this call and if it does then check why it works in admin interface and not in this library...

Sadly i dont have any testing device in my possession to test this for you :/

Maybe? @scop do you have any B525s-23a in your reach to test this ?

**Comment by cagnulein** [comment]
@Salamek are you sue?

isn't this the answer to network()? (copy from my previous comment)

b'<?xml version="1.0" encoding="UTF-8"?>\r\n<response>\r\n<pci>124</pci>\r\n<sc></sc>\r\n<cell_id>205597482</cell_id>\r\n<rsrq>-12dB</rsrq>\r\n<rsrp>-114dBm</rsrp>\r\n<rssi>-81dBm</rssi>\r\n<sinr>4dB</sinr>\r\n<rscp></rscp>\r\n<ecio></ecio>\r\n<mode>7</mode>\r\n<ulbandwidth>20MHz</ulbandwidth>\r\n<dlbandwidth>20MHz</dlbandwidth>\r\n<txpower>PPusch:15dBm PPucch:19dBm PSrs:0dBm PPrach:23dBm</txpower>\r\n<tdd></tdd>\r\n<ul_mcs>mcsUpCarrier1:6</ul_mcs>\r\n<dl_mcs>mcsDownCarrier1Code0:14 mcsDownCarrier1Code1:15 </dl_mcs>\r\n<earfcn>DL:1350 UL:19350</earfcn>\r\n<rrc_status>1</rrc_status>\r\n<rac></rac>\r\n<lac></lac>\r\n<tac>18306</tac>\r\n<band>3</band>\r\n<nei_cellid>No1:0</nei_cellid>\r\n<plmn>22201</plmn>\r\n<ims>0</ims>\r\n</response>\r\n'

**Comment by Salamek** [comment]
@cagnulein i'm not sure :smile_cat: , but there is `b'' Traceback (most recent call last):` in your log... that means empty string was passed to parser just before crash (i assume that b'' comes from our debug print())

best you can do is run it again with only

```
from huawei_lte_api.Client import Client
from huawei_lte_api.AuthorizedConnection import AuthorizedConnection
from huawei_lte_api.Connection import Connection
from huawei_lte_api.api.Net import Net

connection = AuthorizedConnection('http://admin:PASSWORD@192.168.0.254/')
client = Client(connection)
client.net.network()
```
to make log a bit clean... and maybe use `print('START={}=END'.format(response.content))` instead of `print(response.content)` ?

**Comment by scop** [comment]
On Wed, Aug 21, 2019 at 10:02 PM Adam Schubert <notifications@github.com>
wrote:

> Maybe? @scop <https://github.com/scop> do you have any B525s-23a in your
> reach to test this ?
>
Unfortunately not right now, nor in the near future.

**Comment by cagnulein** [comment]
@Salamek here you are:

`START=b'<?xml version="1.0" encoding="UTF-8"?><response><username></username><password_type>4</password_type><firstlogin>1</firstlogin><history_login_flag>0</history_login_flag><wifipwdsamewithwebpwd>1</wifipwdsamewithwebpwd><extern_password_type>1</extern_password_type><State>-1</State><userlevel></userlevel></response>'=END
START=b''=END
Traceback (most recent call last):
  File "router.py", line 19, in <module>
    print(client.net.network())
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/AuthorizedConnection.py", line 20, in wrapped
    return fn(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/api/Net.py", line 15, in network
    return self._connection.get('net/network')
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/Connection.py", line 137, in get
    return self._check_response_status(self._process_response_xml(response.content))
  File "/usr/local/lib/python3.5/dist-packages/huawei_lte_api/Connection.py", line 37, in _process_response_xml
    return xmltodict.parse(xml, dict_constructor=dict)
  File "/usr/local/lib/python3.5/dist-packages/xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0`

**Comment by Salamek** [comment]
@cagnulein there are some timing issues with B525S-23a webserver #56, it may be related to this...

**Comment by cagnulein** [comment]
@Salamek ok, let's investigate about it. I answered on #56 
Thanks for the notification ;)

**Comment by Salamek** [comment]
@cagnulein could you put

`time.sleep(0.5)` on lines:
https://github.com/Salamek/huawei-lte-api/blob/3577ba9828af794bb649f7add396b10c673f8c62/huawei_lte_api/Connection.py#L125
https://github.com/Salamek/huawei-lte-api/blob/3577ba9828af794bb649f7add396b10c673f8c62/huawei_lte_api/Connection.py#L181

(before headers = {})

and don't forgot to add `import time` on line:

https://github.com/Salamek/huawei-lte-api/blob/3577ba9828af794bb649f7add396b10c673f8c62/huawei_lte_api/Connection.py#L1

(before import logging)

And try to run your code... (maybe try higher values like time.sleep(1) just to be sure) @octave21 got his router working with 100ms sleep, but waiting longer wont hurt for testing purposes

**Comment by cagnulein** [comment]
@Salamek i've tested now WITHOUT the sleep (so with the same code that i had on the first post) and everything works fine.

The only change that i made is to use a powerline instead of wifi from my raspberry (where the python script runs) to the router.

This weekend i will try via wifi with my laptop and i will let you know.

This info seems to be in the same @octave21 way (latency creates problems)

**Comment by Salamek** [comment]
@cagnulein ok, i'm closing this, lets continue this issue in #56 since it is issue of a device webserver as a whole thing...
