### ISSUE TITLE
ValueError: 3 is not a valid PasswordTypeEnum

### ISSUE THREAD

**Issue by HenryDelMal** [Salamek/huawei-lte-api#46]
When trying to authenticate after reset a B310 to defaults, AuthorizedConnection fails:

>     connection = AuthorizedConnection('http://192.168.8.1', username="admin",password="admin")
>   File "/usr/local/lib/python3.7/dist-packages/huawei_lte_api/AuthorizedConnection.py", line 24, in __init__
>     if self.user.login(True):
>   File "/usr/local/lib/python3.7/dist-packages/huawei_lte_api/api/User.py", line 83, in login
>     return self._login(PasswordTypeEnum(int(state_login['password_type'])))
>   File "/usr/lib/python3.7/enum.py", line 310, in __call__
>     return cls.__new__(cls, value)
>   File "/usr/lib/python3.7/enum.py", line 564, in __new__
>     raise exc
>   File "/usr/lib/python3.7/enum.py", line 548, in __new__
>     result = cls._missing_(value)
>   File "/usr/lib/python3.7/enum.py", line 577, in _missing_
>     raise ValueError("%r is not a valid %s" % (value, cls.__name__))
> 

It seems the router is returning the value 3 for PasswordTypeEnum because it is expecting to change the password. 

After changing BASE64 enum to 3 it logins perfectly.

**Comment by Salamek** [comment]
Looks like we are missing some enum values in PasswordTypeEnum
We need to find out what 3 means and (my guess is something like "BASE64_USE_NEW_PASSWORD") implement it correctly into lib

Sadly i dont own any testing device, so could you find out ?
Or
Could you dump your router login page for me ? (wia wget with all JS depedencies) and send it to my email?

**Comment by HenryDelMal** [comment]
Sorry about the delay. 

I was testing with wget to the API and the only thing I get is:
```

<?xml version="1.0" encoding="UTF-8"?>
<error>
<code>125002</code>
<message></message>
</error>
```
for both, state-login and login

What would be the correct command for get what you want? I could also grant access you to real hardware via VPN.
