### ISSUE TITLE
Time issue with B525S-23a

### ISSUE THREAD

**Issue by octave21** [Salamek/huawei-lte-api#56]
I am using a B525S-23a Huawei router and your API. Thanks for that great job.

Within the function state_login from Class User.py I was forced to add a wait in order to let the time to the router to answer correctly with a not empty dictionary.

Line number 26 :
``import time``
``time.sleep(0,1)``

Without that, the exception thrown is :
 `('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))` 

Thanks
Octave21
[huwei-lte](https://github.com/octave21/huawei-lte)

**Comment by Salamek** [comment]
https://github.com/psf/requests/issues/4784

**Comment by octave21** [comment]
What can I do for you ?

**Comment by Salamek** [comment]
@octave21 ah, i'm sorry i just put that URL here for reference... maybe i should add some description to it to prevent confusion...
Anyway, it looks like this is issue on server side, so if we want support B525S-23a we will need to introduce some option to enable "hacks" for given device, i'm thinking about something like:
``
AuthorizedConnection('http://admin:pwd@192.168.8.1/', hacks=[HacksEnum.B525S_23A])
``

**Comment by cagnulein** [comment]
@octave21 do you have the issue every time you run a command? To me it happens just sometimes...

**Comment by octave21** [comment]
When my PC is plugged on the B525S via a near CPL (~ 3 meters between the CPL of the PC and the CPL of the B525S), I always experience the issue. When my PC is plugged on the B525S via a "foreign" CPL (~ 40 m between the two CPL) I do not have the issue.
