### ISSUE TITLE
Authorized Connection to devices without a username

### ISSUE THREAD

**Issue by ViktorEvil** [Salamek/huawei-lte-api#58]
is it possible to use an Authorized Connection to devices such the B311s and the B535 which do not have a username section on the web interface

I have tried leaving the username blank etc

connection = AuthorizedConnection('http://my_password@192.168.8.1/')

**Comment by Salamek** [comment]
@ViktorEvil isnt there a hardcoded username in web interface JS code ? like 'admin' or something ?

**Comment by ViktorEvil** [comment]
yes its says 'admin' but using it as such gives an error that says its not authenticated

connection = AuthorizedConnection('http://admin:my_password@192.168.8.1/')

if I use HManager on an old android tablet and leave the username blank it gets authorised but if I use admin for the username it doesn't.

**Comment by Salamek** [comment]
@ViktorEvil can you try huawei-lte-api version 1.4.6 ? (using admin as username)

**Comment by Salamek** [comment]
@ViktorEvil closing this, since i think it was resolved in 1.4.6, fell free to comment for issue reopening when this issue is valid for 1.4.6...
