### ISSUE TITLE
login_on_demand=True no longer "works"

### ISSUE THREAD

**Issue by scop** [Salamek/huawei-lte-api#67]
After we removed the authorized call markers, `login_on_demand=True` no longer actually does what it says, there's nothing that would login on demand/automatically any more. Not sure yet what would be the best fix.

**Comment by Salamek** [comment]
We should probably deprecate that option (throw deprecation warning when True), keep it that way like ~2 versions and then drop it completely... that means remove condition on line: https://github.com/Salamek/huawei-lte-api/blob/b7138e98d51c26b5348612b57187b1287664eb40/huawei_lte_api/AuthorizedConnection.py#L27

I bet that no one is using login_on_demand=True anyway (my code is not using it)...

**Comment by arekm** [comment]
Looking for a replacement for (what I assume) on demand was doing. My script runs 24h and checks lte status on router - when it's bad then forces reconnect with set_mobile_dataswitch or does reboot. Now I'm getting exception with "100003: No rights (needs login)" message after each 5 minutes.

So, is timeout in AuthorizedConnection used for anything? I would assume that it relogs in when something is executed after timeout passes but enforce_authorized_connection() is not called anywhere. It is supposed to be manually called?

**Comment by Salamek** [comment]
@arekm well there is RFC PR #96  with changes to handle all this but it needs some polishing and i don't have time right now, i will try to look at it next weeek...

**Comment by arekm** [comment]
Ok. Just a note that
 
````
AuthorizedConnection()
Client()
try:
  dosomething
except  ResponseErrorLoginRequiredException:
  connection.enforce_authorized_connection()
````

doesn't relog us in if router is rebooted (in middle of "dosomething", even with just client.device.reboot()) and thus we aren't logged in anymore. enforce_authorized_connection() has no knowledge if we are actually logged in in router (only knows if API thinks we are logged in).

So the only safe thing to do as client is to:

````
except  ResponseErrorLoginRequiredException:
  # full connection again
  AuthorizedConnection()
  Client()
````

I don't see "logout" in API, so ugly
````
except  ResponseErrorLoginRequiredException:
  auth_conn.logged_in = False
  connection.enforce_authorized_connection()
````

would also work.

**Comment by Salamek** [comment]
@arekm 1.5 is out with context manager and option to close session...
so you can do 

```python
with Connection('url') as connection:
    client = Client(connection)
    # Do stuff

# auto logout & close session
```

or

```python
connection = Connection('url')
client = Client(connection)
# Do stuff

connection.close() # manually logout & close session
```

Let me know if this release solves your issues....

**Comment by Salamek** [comment]
And login_on_demand has been deprecated and has no effect, it will be removed in next major release, so closing this for now
