### ISSUE TITLE
Send AT Commands

### ISSUE THREAD

**Issue by juanjosepablos** [Salamek/huawei-lte-api#75]
Nice work.
I have been searching on the API, and I could not find a way. I would like to know if I could send:
"AT^NVRDEX=50503,0,128"  without opening the case.
it will show NV codes in hash format.

**Comment by Salamek** [comment]
Option to SEND AT commands is usually available only via modem serial interface (When USB dongle have disabled HiLink interface and is set to legacy mode using pppoe).
I don't think that sending AT commands can be done via REST API that HiLink mode is using, but there may be HiLink alternative to get data you need...  are those NV codes visible somewhere in admin interface?

**Comment by Salamek** [comment]
Closing due to old age

**Comment by Salamek** [comment]
@juanjosepablos oh i have good news, i have found a way how to enable AT command interface on my B310-22 modem! Check out https://github.com/Salamek/huawei-lte-api/blob/master/examples/toggle_telnet.py and https://github.com/Salamek/huawei-lte-api/wiki/AT-Command-interface-Telnet

**Comment by juanjosepablos** [comment]
I will try to find a spare unit and report back. Well Done!

**Comment by Salamek** [comment]
Not sure what set of AT commands is supported or if this works on other huawei devices... 
But if it works for you i would be glad to know what AT commands were working for you except these listed https://github.com/Salamek/huawei-lte-api/wiki/Supported-AT-commands i have just tested
