### ISSUE TITLE
client.sms.send_sms() Not sending message

### ISSUE THREAD

**Issue by raspberrypi3bdii** [Salamek/huawei-lte-api#79]
Hi All,

I'm trying to send a sms with the api. Here is my code:
```

print(client.sms.config())
print(client.sms.send_sms(["+34608113201"], "Hi, check the plug"))
```
this is the output of the prints:
```
{'SaveMode': '0', 'Validity': '10752', 'Sca': '+34656000311', 'UseSReport': '0', 'SendType': '1', 'pagesize': '20', 'maxphone': '50', 'import_enabled': '1', 'url_enabled': '1', 'cdma_enabled': '0', 'smscharlang': '0', 'smsisusepdu': '0', 'sms_center_number_editabled': '0', 'sms_forward_enable': '0', 'switch_enable': '0', 'country_number': None, 'phone_number': None}
OK
```
But there is no SMS on the destination phone

Any idea why?

regards.

**Comment by cagnulein** [comment]
on my 525, your code works flawless
Which router have you got?

**Comment by raspberrypi3bdii** [comment]
Hi @cagnulein 

I have a Huawei-E5576-320, working with a duplicated SIM (Orange is my ISP).

I'm starting to think that maybe is a configuration problem or something related to SIM restrictions (It's duplicate from my phone SIM, but I think only for data services...)

Did you tried with a normal SIM? As I said, there is no errors in the code but i noticed this in the output:

`'country_number': None, 'phone_number': None}`

Can you paste here your output?

Regards.

**Comment by cagnulein** [comment]
Hi @raspberrypi3bdii 

Yes, i tried with a standard sim from WindTre Italy.

My output is:
{'SaveMode': '0', 'Validity': '10752', 'Sca': '+393205858500', 'UseSReport': '0', 'SendType': '1', 'pagesize': '20', 'maxphone': '50', 'import_enabled': '1', 'url_enabled': '1', 'cdma_enabled': '0', 'smscharlang': '0', 'smsisusepdu': '0'}

**Comment by raspberrypi3bdii** [comment]
Hi @cagnulein 

So, my output has more parameters than yours:

```
'sms_center_number_editabled': '0', 
'sms_forward_enable': '0', 
'switch_enable': '0', 
'country_number': None, 
'phone_number': None

```

I think we may found the issue here...

Anyone knows about this parameters?

Regards.

**Comment by Salamek** [comment]
@raspberrypi3bdii Hi,
your code works on my B310-22... so... any news on this?

**Comment by Salamek** [comment]
Closing due to stale state of this issue and age, reopen if issue persists
