### ISSUE TITLE
Can't get signal from Huawei e8372

### ISSUE THREAD

**Issue by baonq243** [Salamek/huawei-lte-api#87]
12d1:14db Huawei Technologies Co., Ltd. E353/E3131

```
print(client.device.signal())
{'pci': None, 'sc': None, 'cell_id': None, 'rsrq': None, 'rsrp': None, 'rssi': None, 'sinr': None, 'rscp': None, 'ecio': None, 'psatt': '1', 'mode': '7', 'lte_bandwidth': None, 'lte_bandinfo': None}
```

**Comment by Salamek** [comment]
@baonq243 sadly i don't have access to the e8372 or E3131 as your device is identifier by `lsusb` ... so i can't help with that right now...
Is your signal info displayed correctly in the admin interface? cos this looks like your device is just not correctly reporting this info instead of issue in this library...

**Comment by baonq243** [comment]
In my hilink app everything is okay.
client.device.information() is work perfect :D but can't get signal
```
>>> from huawei_lte_api.Client import Client
>>> from huawei_lte_api.AuthorizedConnection import AuthorizedConnection
>>> from huawei_lte_api.Connection import Connection
>>> connection = AuthorizedConnection('http://admin:password@192.168.8.1/')
>>> print(client.device.signal())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'client' is not defined
>>> client = Client(connection)
>>> print(client.device.signal())
{'pci': None, 'sc': None, 'cell_id': None, 'rsrq': None, 'rsrp': None, 'rssi': None, 'sinr': None, 'rscp': None, 'ecio': None, 'psatt': '1', 'mode': '7', 'lte_bandwidth': None, 'lte_bandinfo': None}
>>> print(client.device.information())
{'DeviceName': 'E8372', 'SerialNumber': 'xxx', 'Imei': 'xxxx', 'Imsi': 'xxx', 'Iccid': 'xxx', 'Msisdn': '+xxx', 'HardwareVersion': 'CL1E8372HM', 'SoftwareVersion': '21.327.62.00.1460', 'WebUIVersion': '17.100.19.00.1456', 'MacAddress1': 'xxx', 'MacAddress2': None, 'ProductFamily': 'LTE', 'Classify': 'wingle', 'supportmode': 'LTE|WCDMA|GSM', 'workmode': 'LTE'}
>>>
```

**Comment by Salamek** [comment]
@baonq243 hmm maybe your device is using some different endpoint to get signal data? can you check in your browser dev tools what calls are made when you are on signal info page?

**Comment by denklewer** [comment]
My Huawei E8372 LTE Wingle has the same issue. I also have no information about RSSI etc. in HiLink, and I guess this is because this model returns only strength in numbers from 1 to 5

**Comment by denklewer** [comment]
Same issue for E8372 LTE Wingle. I also have no information about RSSI etc.  in my  HiLink.
Javascript code uses api/monitoring/status  and api/device/signal  URLs
And it seems that device only returns signal in numbers from 1 to 5 to draw a signal bar

**Comment by iMiMx** [comment]
Using a E8372-320 or E8372-820, I'm not able to replicate a problem:

`{'pci': '441', 'sc': None, 'cell_id': 'xxxx-014', 'rsrq': '-6.0dB', 'rsrp': '-84dBm', 'rssi': '-59dBm', 'sinr': '19dB', 'rscp': None, 'ecio': None, 'mode': '7', 'ulbandwidth': '15MHz', 'dlbandwidth': '15MHz', 'txpower': 'PPusch:1dBm PPucch:-10dBm PSrs:0dBm PPrach:-9dBm', 'tdd': None, 'ul_mcs': 'mcsUpCarrier1:23', 'dl_mcs': 'mcsDownCarrier1Code0:0 mcsDownCarrier1Code1:0', 'earfcn': 'DL:323 UL:18323', 'rrc_status': None, 'rac': None, 'lac': None, 'tac': '24703', 'band': '1', 'nei_cellid': 'No1:442No2:461', 'plmn': '23415', 'ims': None, 'wdlfreq': None, 'lteulfreq': '19523', 'ltedlfreq': '21423', 'transmode': 'TM[4]', 'enodeb_id': '0010806', 'cqi0': '11', 'cqi1': '12', 'ulfrequency': '1952300kHz', 'dlfrequency': '2142300kHz', 'arfcn': None, 'bsic': None, 'rxlev': None}`

`{'DeviceName': 'E8372h-820', 'SerialNumber': 'xxxx', 'Imei': '869725041684814', 'Imsi': 'xxx', 'Iccid': 'xxxx', 'Msisdn': None, 'HardwareVersion': 'CL4E8372HM', 'SoftwareVersion': '10.0.5.1(H195SP2C983)', 'WebUIVersion': 'WEBUI 10.0.5.1(W13SP5C7401)', 'MacAddress1': '94:E9:EE:68:8E:A9', 'MacAddress2': None, 'WanIPAddress': '10.216.28.166', 'wan_dns_address': '10.206.128.1,10.206.128.1', 'WanIPv6Address': None, 'wan_ipv6_dns_address': None, 'ProductFamily': 'LTE', 'Classify': 'wingle', 'supportmode': 'LTE|WCDMA|GSM', 'workmode': 'LTE', 'submask': '255.255.255.255', 'Mccmnc': '23415', 'iniversion': 'E8372h-820-CUST 10.0.5.1(C1431)', 'uptime': '4857', 'ImeiSvn': '01', 'WifiMacAddrWl0': '94:E9:EE:68:8E:A9', 'WifiMacAddrWl1': None, 'spreadname_en': 'HUAWEI Mobile WiFi 2 mini', 'spreadname_zh': 'HUAWEI Mobile WiFi 2 mini'}`

**Comment by Salamek** [comment]
It was discovered that different Huawei routers sometimes use different endpoints to provide signal info, use [data_dump.py](https://github.com/Salamek/huawei-lte-api/blob/master/examples/data_dump.py) to dump all data your router provides and find with is returning signal info correctly or check what requests is your WebUI doing in your browser dev tools to find out what call to use.
