### ISSUE TITLE
Is there a way to use proxy with API calls.

### ISSUE THREAD

**Issue by bashar-ait** [Salamek/huawei-lte-api#97]
Hello there,

How can i send an API request through a proxy? just like how we can using requests package.

`requests.get(url,proxies=proxies)`

Is there a way to do the same with the api?

```
connection = AuthorizedConnection(f'http://admin:admin@{ip}',proxies=proxy)
client.sms.send_sms(numbers,message)
```

**Comment by Salamek** [comment]
@bashar-ait  in version 1.5 there is new option to pass custom `requests.Session`, that should solve your issue, see this howto example code: https://github.com/Salamek/huawei-lte-api/blob/master/examples/connect_with_proxy.py
