### ISSUE TITLE
Feature request: receive SMS in home assistant

### ISSUE THREAD

**Issue by hvanoch** [Salamek/huawei-lte-api#99]
Are you willing to support more features in home assistant?
One of the biggest feature I am missing is the "Receive SMS" functionality. 

Would you be willing to support this if I come up with a PR?

My idea is to have similar approach as the current [SMS integration](https://www.home-assistant.io/integrations/sms/#notifications)

I guess the only option is to poll every x time and when we notice we received a new SMS send an event and delete the SMS. Simular to the [SMS integration](https://github.com/home-assistant/core/blob/dev/homeassistant/components/sms/gateway.py)

**Comment by Salamek** [comment]
@scop i think this is Q on you... :smile

**Comment by elmpp** [comment]
@scop @hvanoch 

I can offer my help with implementing this also...

**Comment by scop** [comment]
I can have a look if someone submits a HA PR, but I don't have an easy way to test that so unsure how much I can help. Anyway I think this issue and the upcoming PR would be better placed in the HA project rather than here.

**Comment by Salamek** [comment]
Closing this since this is HA q...
